`define false 1'b 0
`define FALSE 1'b 0
`define true 1'b 1
`define TRUE 1'b 1

`timescale 1 ns / 1 ns // timescale for following modules


//  VHDL Entity R6502_TC.R6502_TC.symbol
// 
//  Created:
//           by - eda.UNKNOWN (ENTWICKL4-XP-PR)
//           at - 11:47:57 23.02.2009
// 
//  Generated by Mentor Graphics' HDL Designer(TM) 2007.1a (Build 13)
// 

module R6502_TC (
   clk_clk_i,
   d_i,
   irq_n_i,
   nmi_n_i,
   rdy_i,
   rst_rst_n_i,
   so_n_i,
   a_o,
   d_o,
   rd_o,
   sync_o,
   wr_o);
 

input   clk_clk_i; 
input   [7:0] d_i; 
input   irq_n_i; 
input   nmi_n_i; 
input   rdy_i; 
input   rst_rst_n_i; 
input   so_n_i; 
output   [15:0] a_o; 
output   [7:0] d_o; 
output   rd_o; 
output   sync_o; 
output   wr_o; 


//  Jens-D. Gutschmidt     Project:  R6502_TC  
//  scantara2003@yahoo.de                      
//  COPYRIGHT (C) 2008-2009 by Jens Gutschmidt and OPENCORES.ORG                                                                                
//                                                                                                                                              
//  This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by   
//  the Free Software Foundation, either version 3 of the License, or any later version.                                                        
//                                                                                                                                              
//  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of              
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.                                  
//                                                                                                                                              
//  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.     
//                                                                                                                                              
//  CVS Revisins History                                                                                                                        
//                                                                                                                                              
//  $Log: not supported by cvs2svn $                                                                                                                         
//    <<-- more -->>                                                                                                                            
//  Title:  Top Level  
//  Path:  R6502_TC/R6502_TC/struct  
//  Edited:  by eda on 10 Feb 2009  
// 
//  VHDL Architecture R6502_TC.R6502_TC.struct
// 
//  Created:
//           by - eda.UNKNOWN (ENTWICKL4-XP-PR)
//           at - 11:47:58 23.02.2009
// 
//  Generated by Mentor Graphics' HDL Designer(TM) 2007.1a (Build 13)
// 
wire    [15:0] a_o; 
wire    [7:0] d_o; 
wire    rd_o; 
wire    sync_o; 
wire    wr_o; 

//  Declarations

//  Optional embedded configurations
//  pragma synthesis_off

//  pragma synthesis_on
//  Instance port mappings.

Core U_0 (.clk_clk_i(clk_clk_i),
          .d_i(d_i),
          .irq_n_i(irq_n_i),
          .nmi_n_i(nmi_n_i),
          .rdy_i(rdy_i),
          .rst_rst_n_i(rst_rst_n_i),
          .so_n_i(so_n_i),
          .a_o(a_o),
          .d_o(d_o),
          .rd_o(rd_o),
          .sync_o(sync_o),
          .wr_o(wr_o));

//  Architecture declarations
//  Internal signal declarations
//  Component Declarations

endmodule // module R6502_TC

